window.FX_DATA = {
  meta: {
    reportDate: "2026-09-16",
    reportLabel: "UK CPI CAME IN EXACTLY AT FORECAST, 3.1% from 2.9%, and the pound is the best G10 on the day at +0.09% - the confirmation this file asked for yesterday, delivered. But the detail matters: core held 2.6% against a 2.7% forecast, so the headline supports the three MPC hawks while the core undershoot gives the six holders their cover. GBP stays 0 into tomorrow's 11:00Z vote. Second, the dollar's streak is over. After beating all seven peers two sessions running, DXY is 99.569 and DOWN 0.07% today, with GBP +0.09%, EUR +0.05%, CHF +0.05%, AUD +0.01%, CAD -0.03%, JPY -0.04% and NZD -0.07%. USD holds +2 and is NOT promoted - the dot plot lands in twelve hours. Third, and this is the real change: the haven failure has stopped. Gold 4329.73 is UP 0.87% and silver 64.584 UP 1.48% while WTI 104.779 fell 0.99%, the first session of the run where bullion rose and oil fell together. Yesterday's XAU and XAG shorts are STOOD DOWN to RANGE into a binary event with managed-money positioning at roughly 228k net long. Copper is stood down too - the tariff-review unwind that took XCU 5.76% lower on the week has now delivered, and the physical market is tight with LME stocks near 90,000t. Board: USD +2; EUR, AUD, CAD, JPY +1; GBP, CHF 0; NZD -1. With four central banks and a GDP print inside 65 hours, the cleanest trades are the ones with NO event leg: EUR/CHF, AUD/CHF and CAD/CHF LONG, plus USOIL LONG on supply. FOMC 18:00Z, NZ GDP 22:45Z, BoE Thursday 11:00Z, BoJ Friday 02:30Z.",
    horizon: "4H swing",
    coverage: "USD, EUR, GBP, JPY, AUD, NZD, CAD, CHF · 28 pairs (full G10 ex SEK/NOK) + DXY + JPYBASKET + GER40 + XAU + XAG + XCU + USOIL",
    regime: "The regime is still a physical energy supply shock priced through US real rates, but for the first time in this run two of its supporting legs wobbled on the same session. The dollar stopped beating everything - DXY 99.569 is down 0.07% and lost ground to five of seven peers - and bullion stopped falling, with gold up 0.87% and silver up 1.48% against a WTI that slipped 0.99%. Neither is yet a reversal: the dollar is still up 0.76% on the week against all seven, and gold is still down 1.56% on the week and 1.95% on the month. What it is, is a market flattening exposure before a dot plot. The second feature is that the calendar has collapsed into a single window - the Fed decides in twelve hours, New Zealand prints Q2 GDP five hours after that, the Bank of England votes in twenty-nine hours and the Bank of Japan in forty-four, and every one of them is priced: 86-90% on the Fed, 0.1% consensus on NZ GDP, 3-0-6 on the MPC, 97% on the BoJ. When every level is bought, the only tradeable content is guidance, and the only clean trades are the ones with no central bank attached to them.",
    nextBigEvent: "FOMC decision, statement and the Summary of Economic Projections today, Wednesday September 16 at 18:00Z, with the Warsh press conference at 18:30Z. ForexFactory carries a 4.00% forecast against a 3.75% previous, TE carries the same, and CME FedWatch has held between 86% and 90% since the September 11 inflation release, so the hike itself is bought and the event is the dot plot alone. The tension is unchanged and unresolved: the Fed's own published projection rows - 3.8% current year, 3.6% first year, 3.4% second, 3.1% third, 3.1% longer-run - describe a path that CUTS after today, while the futures strip prices two quarter-point increases by year end. One of those has to give and there is no verbal channel to hedge with, because Warsh has abandoned his predecessor's forward-guidance style and has said nothing since Jackson Hole on August 28. If the out-year dots are lifted to flat or higher, USD goes to +3 and re-rates every dollar pair here. If the easing path survives intact, today is read as the last hike and sold, which hits DXY LONG, USD/CHF LONG, EUR/USD SHORT, AUD/USD SHORT and NZD/USD SHORT simultaneously - that remains the single largest correlated risk in this file, and it is the reason the dollar book was trimmed from HIGH to MEDIUM rather than held.",
  },

  dailyRead: "Start with the print, because for once the day's scheduled event landed before this file was written. UK August CPI came in at 3.1% year on year against a 3.1% forecast and 2.9% previously, with the monthly rate at 0.5% from 0.3%. That is exactly the number yesterday's file said would preserve the score and the vote - and it did - but the composition is more interesting than the headline. Core inflation held at 2.6% against a 2.7% forecast, so it did not accelerate at all. Put the two together and you have a headline driven by energy passing through into a core that is going nowhere, which is precisely the split the Monetary Policy Committee has been arguing about since July. The three hawks - Pill, Greene and Mann - get a 3.1% headline at a fifteen-month high to point at. The six holders get a core that missed and a claimant count that blew out to +27.8k yesterday against an +8.3k forecast. Nothing in this morning's data moves a single vote, which is why the consensus is still 3-0-6 for a hold at 3.75% tomorrow at 11:00Z, and why GBP stays at 0. What sterling did do is outperform: it is the best G10 currency on the day at +0.09% and still the best on the week at -0.42% against the dollar, GBP/USD 1.34899. A currency that takes a broken labour print on Tuesday and an unaccelerating core on Wednesday and still leads the board is a currency with a bid under it, and that is the single reason GBP/USD SHORT is cut to LOW-MED and EUR/GBP LONG with it. Second, the dollar's streak is over, and this file should say so plainly because it spent two days building the case for it. DXY is 99.569, down 0.07%, and it lost ground to five of seven peers today: GBP +0.09%, EUR +0.05%, CHF +0.05%, AUD +0.01%, against CAD -0.03%, JPY -0.04% and NZD -0.07%. The weekly board is untouched - the dollar is still up 0.76% and still higher against all seven over five sessions - so this is a pause, not a turn, and USD holds +2. It is emphatically not promoted to +3, for the same reason as yesterday and now with more force: DXY is minus 0.07% on the month while carrying an 86-to-90% probability of a hike to 4.00%, which says the move is fully bought and nothing beyond it is priced. That question resolves at 18:00Z tonight and there is no way to pre-position for it, which is the organising fact of this entire file. Third, and this is the day's genuine change of view, the haven failure has stopped. Gold is 4329.73, up 0.87%; silver is 64.584, up 1.48%; and they did that while WTI fell 0.99% to 104.779. Every prior session of this run had the opposite sign - bullion down, oil up, insurance being paid in energy rather than metal. One session does not overturn a month, and the weekly numbers still favour the short: gold minus 1.56%, silver minus 3.99%. But the reason to act is not the bounce, it is what the bounce is made of. Managed-money positioning in silver is crowded long at roughly 228,000 net contracts into a binary event, and a crowded long that starts rising the morning of the event is the market hedging, not capitulating. Holding a directional metals short through a dot plot that could move real rates either way, against that positioning, is a bad risk for a 4H book. So XAU/USD and XAG/USD are STOOD DOWN from SHORT to RANGE. That is a de-risking into an event, not a reversal: the real-rates thesis is intact and the shorts come back if the dots are lifted. Fourth, copper is stood down as well, and here the reasoning is structural rather than tactical. XCU is 6.4118, up 0.68% today but down 5.76% on the week, and the week's collapse now has an identified cause - reports that the United States is reconsidering the refined-metal import tariffs that had been pulling hundreds of thousands of tonnes across the Atlantic, which knocked futures almost 5% in a session. That matters because the tariff-arbitrage trade was the short's whole engine. Once the arbitrage unwinds, what is left is the physical market, and the physical market is tight: LME live stocks have been drained to roughly 90,000 tonnes, global mine output contracted 1.1% in the first half with Chile down 6.6%, Indonesian concentrate down 32% and DRC down 34%. A positioning short whose catalyst has already been paid, standing in front of a 90,000-tonne inventory, is a short that snaps - yesterday's file said so in terms, and today it acts on its own warning. XCU/USD goes to RANGE. Fifth, oil. WTI fell 0.99% today after rising 9.09% on the week and 24.00% on the month, and Brent is 108.126, down 0.57%. Nothing in the supply picture has changed: Saudi Arabia's East-West pipeline - the route that bypasses Hormuz - is still shut with no restart timeline from Aramco, Houthi attacks on Saudi Arabia resumed this week, Libya's national oil company has suspended two oilfields and a pumping station amid protests, and the US and Iran are exchanging tanker-for-tanker strikes around the strait under a policy Washington approved this month. A one-percent down day inside that is profit-taking after a 24% month, not a resolution. USOIL LONG stays, and it is now the ONLY high-conviction trade in the file, precisely because it is the one position whose thesis does not depend on a central bank speaking in the next three days. Which brings the book to its organising idea. The board is USD +2; EUR, AUD, CAD and JPY +1; GBP and CHF 0; NZD -1. Almost every gap on it has an event attached inside sixty-five hours - a dollar leg resolves at 18:00Z, a kiwi leg at 22:45Z, a sterling leg tomorrow at 11:00Z and a yen leg on Friday at 02:30Z. The trades that survive that filter are the CHF crosses, because the SNB does not meet until September 24 and is universally expected to sit at 0.00%: EUR/CHF, AUD/CHF and CAD/CHF LONG are event-free expressions of the same view the dollar book expresses with event risk, and CAD/CHF is upgraded to MEDIUM on that basis alone. On the currencies themselves: the euro holds +1 on a genuinely hawkish central bank - a unanimous hike to a 2.50% deposit rate on September 10, the 2027 inflation projection lifted to 2.5%, 2026 growth upgraded to 0.9% - against an energy bill that keeps worsening, with EU gas at 82.69 up 3.29% today, 33.89% on the month and 155% on the year. Australia holds +1 with the top carry on the board at 4.35% and a copper bounce beneath it. Canada holds +1 on energy terms of trade alone, and it slips below Australia within the tier today because oil fell and copper rose - its domestic data is still contracting outright with employment minus 41.7k, services PMI 46.8 and composite 47.8, and the Bank of Canada is frozen at 2.25% until October 28. Japan holds +1: wage growth 4.7%, CPI 1.9%, core 1.8%, unemployment 2.4%, and a hike to a 31-year high on Friday that 97% of economists expect - but speculators have flipped net long yen for the first time since February, which is the definition of a crowded trade into a priced event, so the yen crosses stay RANGE rather than short. Switzerland stays at 0 on the same contradiction as yesterday: the best data on the board - GDP up 1.5% on the quarter and 2.3% on the year, manufacturing PMI 57.1, unemployment 3.0% - attached to a 0% policy rate and a central bank that has signalled it will intervene against appreciation. Good economy, unownable currency, ideal funding leg. And New Zealand stays at minus 1 and worst on the board, down 0.07% today, 1.49% on the week and 2.52% on the month at 0.57531, with Q2 GDP tonight at 22:45Z forecast at +0.1% against +0.8% previously. The warning on that one is specific: ASB expects 0.3%, above both the consensus and the RBNZ's own flat estimate, so the risk on the kiwi short is an upside surprise arriving five hours after the Fed. That is why NZD/USD comes down from HIGH to MEDIUM - not because the view changed, but because two binary events now sit inside one session and the position cannot be managed through both.",

  snapshot: [
    {
      icon: "🇬🇧",
      t: "UK CPI landed exactly on forecast at 3.1%, but core held 2.6% against a 2.7% call",
      s: "Headline accelerated from 2.9% with the monthly rate at 0.5% from 0.3%, a fifteen-month high that hands the three MPC hawks their argument. The core undershoot hands the six holders theirs, so the 3-0-6 consensus for tomorrow is untouched and GBP stays 0.",
    },
    {
      icon: "💵",
      t: "The dollar's two-day clean sweep is over - DXY fell 0.07% and lost to five of seven peers",
      s: "DXY 99.569, with GBP +0.09%, EUR +0.05%, CHF +0.05% and AUD +0.01% against it. The weekly board is untouched at +0.76% and higher against all seven, so this is a pause before the dots, not a turn. USD holds +2 and is not promoted.",
    },
    {
      icon: "🥇",
      t: "Bullion caught a bid for the first time in the run while crude fell - gold +0.87%, silver +1.48%",
      s: "Gold 4329.73 and silver 64.584 rose as WTI slipped 0.99%, inverting the sign that has defined this regime. With managed money crowded long near 228k net contracts into a binary dot plot, the XAU and XAG shorts are stood down to RANGE rather than carried.",
    },
    {
      icon: "🛢️",
      t: "WTI fell 0.99% to 104.779 on profit-taking, with every supply leg still in place",
      s: "The Saudi East-West pipeline that bypasses Hormuz remains shut with no Aramco restart timeline, Houthi strikes on Saudi Arabia resumed this week, Libya suspended two oilfields, and US-Iran tanker-for-tanker strikes continue. One down day inside a 24.00% month is positioning, not resolution.",
    },
    {
      icon: "🔻",
      t: "Copper is stood down: the tariff-review unwind has been paid and the physical market is tight",
      s: "XCU 6.4118, up 0.68% today but down 5.76% on the week after reports Washington is reconsidering refined-metal import tariffs knocked futures almost 5%. With LME stocks drained near 90,000t and mine supply down 1.1% in H1, the short's catalyst is spent. RANGE.",
    },
    {
      icon: "🇳🇿",
      t: "New Zealand is worst again into a GDP print that one major bank expects to beat consensus",
      s: "NZD/USD 0.57531, down 0.07% today, 1.49% on the week and 2.52% on the month. Q2 GDP at 22:45Z is forecast +0.1% from +0.8%, but ASB expects 0.3% - above both consensus and the RBNZ's flat estimate. That upside risk lands five hours after the Fed, so NZD/USD is cut to MEDIUM.",
    },
    {
      icon: "⏱️",
      t: "Four central banks and a GDP print inside 65 hours leave only the CHF crosses event-free",
      s: "Fed 18:00Z tonight, NZ GDP 22:45Z, BoE tomorrow 11:00Z, BoJ Friday 02:30Z - and all four are priced at 86-90%, consensus, 3-0-6 and 97% respectively. The SNB does not meet until September 24, which is why EUR/CHF, AUD/CHF and CAD/CHF LONG are the cleanest tickets on the board.",
    },
  ],

  ratePaths: {
    USD: {
      next: "hike",
      when: "Today, Sept 16 at 18:00Z, with the press conference at 18:30Z - ForexFactory carries a 4.00% forecast against 3.75% previous, TE carries the same, and CME FedWatch has held 86-90% since September 11",
      note: "TE re-verified today: policy rate 3.75% upper bound, CPI 3.4% y/y with core 2.4%, unemployment 4.1%, non-farm payrolls +162,000, GDP 1.5% q/q and 2.1% annual, manufacturing PMI 53.9, services 56.5, composite 56.0, retail sales -0.6% m/m, consumer confidence 47.8. The hike is bought; the event is the Summary of Economic Projections. The Fed's published rows - 3.8% current year, 3.6% first, 3.4% second, 3.1% third, 3.1% longer-run - describe a path that cuts after today, while the futures strip prices two more quarter-point increases by year end. Warsh has abandoned forward guidance entirely and has not spoken since Jackson Hole on August 28, so the dots are the only channel. Beyond today, the strip implies a second hike at the October 28 meeting or in December.",
    },
    EUR: {
      next: "hold",
      when: "Oct 29 - the ECB hiked to a 2.50% deposit rate on September 10 and the Governing Council calendar puts the next monetary policy meeting on October 29, with TE carrying no further move before then",
      note: "TE re-verified today: deposit facility rate 2.50% from 2.25%, taken from TE's Deposit Facility Rate row rather than the 2.65% main refinancing rate. Headline HICP 3.3% y/y for August with core at 2.40% from 2.50%, GDP 0.6% q/q and 1.2% annual, unemployment 6.4%, Q2 employment +0.1%, manufacturing PMI 52.7, services 51.6, composite 52.0, retail sales -0.6% m/m. The September 10 hike was unanimous, Lagarde called it a no-brainer, the 2027 inflation projection was lifted to 2.5% and 2026 growth upgraded to 0.9%. The final August HICP prints tomorrow at 09:00Z with a 3.3% forecast - a confirmation rather than an event. The live tension is energy: EU gas 82.69 is up 33.89% on the month, which is a direct terms-of-trade tax on the same economy the ECB just upgraded.",
    },
    GBP: {
      next: "hold",
      when: "Tomorrow, Sept 17 at 11:00Z - TE carries a 3.75% forecast and ForexFactory carries the vote consensus unchanged at 3-0-6, three for a hike to 4.00% and six to hold",
      note: "TE re-verified today: Bank Rate 3.75%, and August CPI released this morning at 3.1% y/y against a 3.1% forecast and 2.9% previously, with the monthly rate 0.5% from 0.3% and core holding 2.6% against a 2.7% forecast. Unemployment 4.9%, employment change +67k, average earnings 3.9% from 4.2%, and yesterday's claimant count +27.8k against +8.3k. GDP 0.4% q/q and 1.2% annual, manufacturing PMI 51.7, services 52.5, composite 52.5. The committee votes with a fifteen-month-high headline and an unaccelerating core, which is why nothing moved: Pill, Greene and Mann keep their case, the six holders keep theirs. The Bank has projected inflation peaking near 3.2% in Q4. The tradeable content tomorrow is the vote split, not the level - a fourth hawkish defector would be the surprise.",
    },
    JPY: {
      next: "hike",
      when: "Friday, Sept 18 at 02:30Z with the press conference at 05:30Z - ForexFactory carries a 1.25% forecast against 1.00% previous, and 97% of surveyed economists plus roughly 97% of OIS pricing agree",
      note: "TE re-verified today: policy rate 1.00%, CPI 1.9% y/y with core 1.8%, unemployment 2.4%, wage growth 4.7% from 4.0%, GDP 0.4% q/q and 0.7% annual, manufacturing PMI 54.9, services 52.5, composite 53.5, retail sales +2.4% m/m and +4.0% y/y. A move to 1.25% would be the highest policy rate since April 1995. Supporting it: Q2 GDP revised up to 1.4% annualised, July real wages +2.4% - the strongest since 2021 - and August wholesale prices +7.6% y/y. The problem for the currency is that 89% of analysts already see 1.50% by end-March and speculators have flipped net long yen for the first time since February 2026, so the position is crowded and the level is bought. The tradeable content is whether a pause is attached to the statement.",
    },
    AUD: {
      next: "hold",
      when: "Sept 29 at 04:30Z - the RBA board meets September 28-29 and TE carries no change from 4.35%, which remains the highest policy rate on this board",
      note: "TE re-verified today: RBA cash rate 4.35%, CPI 3.5% y/y from 3.8% with trimmed-mean core at 3.6%, unemployment 4.5% from 4.4%, employment change -15,827 persons after +80,249, wage growth 3.2%, GDP 0.4% q/q and 2.1% annual, manufacturing PMI 52.0, services 53.2, composite 52.7, consumer confidence 84.4 from 88.9. Headline inflation is falling but core is sticky at 3.6% and above the 2-3% band, which keeps the RBA on hold rather than easing. The external read is the swing factor: China August industrial production beat at 5.2% while retail sales missed at 0.4% and fixed asset investment deepened to -7.2%, and copper bounced 0.68% today after a 5.76% weekly fall. Top carry plus a tight copper market is the whole AUD case.",
    },
    NZD: {
      next: "hold",
      when: "Oct 28 at 01:00Z - TE carries a 2.75% forecast for October, with the RBNZ's own Q4 average OCR projection of 2.81% implying the next hike at the December 9 meeting rather than October",
      note: "TE re-verified today: OCR 2.75% after the September 2 hike from 2.50%, CPI 4.1% y/y with core 3.2%, unemployment 5.6% from 5.4%, Q2 employment +0.5%, wage growth 2.1%, GDP 0.8% q/q and 1.5% annual, manufacturing PMI 53.1, services 51.2, composite 52.5, consumer confidence recovering to 89.5 from 80.4. The September 2 statement lifted the OCR citing fuel-driven inflation from the Middle East conflict and signalled it may tighten further before year end, but the medium-term growth outlook was marked down. Q2 GDP tonight at 22:45Z is the immediate test at a +0.1% consensus against +0.8% previously; ASB expects 0.3%, above both consensus and the RBNZ's flat estimate, and a beat of that size would pull December pricing forward.",
    },
    CAD: {
      next: "hold",
      when: "Oct 28 - the Bank of Canada's calendar carries the next overnight rate announcement with a Monetary Policy Report, and TE carries no change from 2.25%",
      note: "TE re-verified today: BoC overnight rate 2.25%, CPI 3.0% y/y with core rising to 2.4% from 2.3%, unemployment 6.4%, employment -41.7k after +75.1k, wage growth 3.4%, GDP 0.8% q/q and 1.1% annual, manufacturing PMI 53.0, services 46.8, composite 47.8, retail sales -0.8% m/m and +5.2% y/y, consumer confidence 48.2 from 49.4. This is the split that defines the Canadian dollar: headline inflation at 3.0% and an energy windfall from a WTI up 24.00% on the month against a domestic economy where services and composite PMIs are both in contraction and employment fell by 41.7k. The Bank is frozen between the two until October 28, which is why CAD trades on crude rather than on its own data - and why it slipped within the +1 tier today as oil fell 0.99%.",
    },
    CHF: {
      next: "hold",
      when: "Sept 24 at 07:30Z - TE carries both a 0% consensus and a 0% forecast, and all but one of 41 economists in the Reuters poll expect the policy rate to stay at zero through 2026",
      note: "TE re-verified today: SNB policy rate 0.00%, CPI 0.8% y/y with core 0.4%, unemployment 3.0%, Q2 employment +0.5%, GDP 1.5% q/q and 2.3% annual - the strongest growth mix on this board - manufacturing PMI 57.1 from 53.2, services 58.3, retail sales +0.1% m/m and +2.3% y/y. The bar for going negative again is high with inflation picking up, so the September 24 meeting is about the other lever: the SNB has signalled greater willingness to intervene in FX to stop the franc appreciating on the Middle East haven bid, and sight deposits have been rising. A central bank that is explicitly capping its own currency while paying zero to hold it is what makes CHF the funding leg of this file regardless of how good the Swiss data is.",
    },
  },

  today: [
    {
      ccy: "GBP",
      moved: true,
      headline: "August CPI printed 3.1% y/y against a 3.1% forecast and 2.9% previously, monthly 0.5% from 0.3%, but core held 2.6% against a 2.7% forecast - and sterling is the best G10 on the day at +0.09%",
      read: "The confirmation this file asked for yesterday arrived, and it split the difference: a fifteen-month-high headline for the three hawks, an unaccelerating core for the six holders. Nothing here moves a vote, so the 3-0-6 consensus for tomorrow at 11:00Z stands and GBP holds 0. What has changed is the price behaviour - a currency that absorbs a broken claimant count on Tuesday and a soft core on Wednesday and still leads the board is being accumulated, which is why GBP/USD SHORT and EUR/GBP LONG are both cut to LOW-MED. The next risk is the vote split itself: a fourth hawkish defector takes GBP to +1, while an unchanged 3-0-6 with dovish minutes is the first genuine sell signal sterling has carried.",
    },
    {
      ccy: "USD",
      moved: true,
      headline: "DXY 99.569, down 0.07%, ending the two-session run of beating all seven peers - it lost to GBP, EUR, CHF and AUD today, and is now -0.07% on the month",
      read: "A pause rather than a turn: the weekly board is untouched with the dollar up 0.76% and still higher against all seven over five sessions. USD holds +2 and is explicitly not promoted, because the month is flat while an 86-90% hike to 4.00% is fully priced - the market has bought the level and nothing past it. Everything resolves at 18:00Z tonight. Out-year dots lifted to flat or higher takes USD to +3 and re-rates nine positions in this file at once; an intact easing path makes today the last hike and gets sold, hitting the same nine from the other side. That correlation is why the dollar book sits at MEDIUM rather than HIGH tonight.",
    },
    {
      ccy: "NZD",
      moved: true,
      headline: "Worst G10 again at -0.07%, with NZD/USD 0.57531 down 1.49% on the week and 2.52% on the month - and Q2 GDP tonight at 22:45Z forecast at +0.1% against +0.8% previously",
      read: "The structural case is unchanged and is the widest gap on the board: an RBNZ that hiked to 2.75% on September 2 because of imported fuel inflation, then signalled a pause into October with the next move not priced until December 9, sitting on 4.1% headline inflation, 3.2% core and unemployment rising to 5.6%. A central bank that stops tightening into 4% inflation because the economy cannot absorb more is a currency you stay short. The specific near-term risk is a beat: ASB looks for 0.3% against a 0.1% consensus and the RBNZ's own flat estimate, and that lands five hours after the Fed. NZD/USD is cut to MEDIUM on event stacking, not on any change of view; the crosses carry the same view with fewer legs.",
    },
    {
      ccy: "CHF",
      moved: false,
      headline: "Up 0.05% against the dollar at USD/CHF 0.81831 as gold rose 0.87% and crude fell - a mild haven bid, but still down 1.01% on the week",
      read: "The contradiction holds: Switzerland has the best data on this board with GDP up 1.5% on the quarter and 2.3% on the year, manufacturing PMI 57.1 and unemployment 3.0%, and the franc is still scored at zero because the policy rate is 0.00% against a Fed going to 4.00%, and because the SNB has signalled it will lean against appreciation before it meets on September 24. That combination - no yield, an explicit cap, and no meeting for eight days - is what makes CHF the one currency in this file with no binary event attached, and therefore the ideal funding leg. EUR/CHF, AUD/CHF and CAD/CHF LONG are the cleanest tickets on the board tonight for exactly that reason.",
    },
    {
      ccy: "EUR",
      moved: false,
      headline: "Second-best on the day at +0.05%, EUR/USD 1.15493, but EU gas jumped another 3.29% to 82.69 and is now up 33.89% on the month",
      read: "The two sides of the euro are both getting stronger, which is why it stays at +1 rather than moving. On the policy side the ECB is genuinely hawkish - a unanimous hike to a 2.50% deposit rate on September 10, the 2027 inflation projection lifted to 2.5%, 2026 growth upgraded to 0.9%, and no further move expected until October 29. On the real side the energy bill is a direct terms-of-trade tax that is compounding, with gas up 33.89% on the month and 155% on the year, and August HICP already at 3.3% with energy inflation at 14.3%. The final August print tomorrow at 09:00Z should confirm 3.3% and is not an event. EUR expresses itself best against the franc, where neither leg carries a meeting this week.",
    },
    {
      ccy: "AUD",
      moved: false,
      headline: "Effectively flat at +0.01%, AUD/USD 0.71322, with copper bouncing 0.68% after a 5.76% weekly fall",
      read: "Australia holds +1 on the highest carry on the board at 4.35% with the RBA parked until September 29, sticky trimmed-mean core at 3.6% keeping any easing off the table, and a softening labour market - employment -15,827 after +80,249, unemployment up to 4.5% - capping the upside. The external read improved at the margin today: copper rose, and the reason the week was bad is now identified as a tariff-review unwind rather than a demand collapse, which is a better backdrop for the Australian dollar than it looked on Monday. China remains the swing factor with August production beating at 5.2% and retail sales missing at 0.4%. AUD/CHF LONG is the cleanest expression; AUD/USD SHORT carries the dot plot.",
    },
    {
      ccy: "CAD",
      moved: false,
      headline: "Down 0.03% at USD/CAD 1.39223 as WTI slipped 0.99% to 104.779, the first down day in a month that is still up 24.00%",
      read: "Canada slips to the back of the +1 tier today, behind Australia, for a specific reason: its entire case is energy terms of trade and energy fell, while the domestic picture is contracting outright - employment -41.7k, services PMI 46.8, composite 47.8, retail sales -0.8% m/m - with the Bank of Canada frozen at 2.25% until October 28. That is not a downgrade, because the supply shock behind crude is fully intact with the Saudi East-West pipeline still shut and Libya suspending fields, and a one-percent pullback after a 24% month is positioning. But it does mean CAD is a derivative of WTI rather than an independent currency, so CAD/CHF LONG is preferred to any Canadian trade with a second event leg in it.",
    },
    {
      ccy: "JPY",
      moved: false,
      headline: "Down 0.04% at USD/JPY 155.157, still -2.69% on the month, with the BoJ 97% priced to hike to a 31-year high on Friday",
      read: "The fundamentals are the best on this board in direction - wage growth 4.7% from 4.0%, CPI 1.9% from 1.6%, core 1.8%, unemployment 2.4%, Q2 GDP revised up to 1.4% annualised, wholesale prices +7.6% - and none of it is tradeable, because 97% of economists and roughly 97% of OIS agree on 1.25% and speculators have flipped net long yen for the first time since February 2026. A fully-priced hike held by a crowded long has no buyers left in it, which is why JPY sits at +1 alongside the euro, the Aussie and the Canadian dollar rather than above them, and why the yen-cross book is RANGE almost throughout. Only NZD/JPY survives as a directional short, on a two-point gap. The one thing that can still move the yen on Friday is the statement language on what comes after 1.25%.",
    },
  ],

  strength: [
    {
      ccy: "USD",
      score: 2,
      verdict: "STRENGTHENING",
      tag: "Streak broken, weekly intact, dots tonight",
      drivers: "Policy rate 3.75% upper bound with FedWatch at 86-90% for tonight's move to 4.00%, CPI 3.4% y/y with core 2.4%, unemployment 4.1%, payrolls +162,000, services PMI 56.5 and composite 56.0; DXY 99.569, down 0.07% today after two sessions of beating all seven peers, still +0.76% and higher against all seven on the week, but -0.07% on the month.",
      forward: "⚖️ Tightening on policy, balanced on price, and deliberately held rather than promoted. The two-day sweep ended today - the dollar lost ground to GBP, EUR, CHF and AUD - which does not undo a weekly board that is still positive against all seven, but does say the market has stopped buying dollars ahead of the event. The reason USD is not raised to +3 is unchanged and now sharper: DXY is -0.07% on the month while an 86-90% hike is priced, so the level is bought and nothing beyond it is. Tonight's Summary of Economic Projections is the entire trade. The Fed's own rows - 3.8% current year, 3.6% first, 3.4% second, 3.1% third, 3.1% longer-run - describe a path that cuts after today, against a futures strip pricing two more increases by year end; one has to give, and Warsh has abandoned forward guidance so there is no verbal hedge. The dovish hook is real: core CPI at 2.4% is the lowest since March 2021, giving a committee that wants to look through an oil shock the data to do it. What would invalidate: an intact easing path in the dots is the sell-the-fact scenario and hits DXY, USD/CHF, EUR/USD, AUD/USD and NZD/USD together - the single largest correlated risk here, and the reason the dollar book is at MEDIUM tonight. Out-year dots lifted to flat or higher takes USD to +3.",
    },
    {
      ccy: "EUR",
      score: 1,
      verdict: "MIXED",
      tag: "Hawkish bank, compounding energy tax",
      drivers: "ECB deposit facility rate 2.50% from 2.25% after the unanimous September 10 hike, HICP 3.3% y/y for August with core easing to 2.4% from 2.5% and energy inflation at 14.3%, GDP 0.6% q/q and 1.2% annual, unemployment 6.4%, composite PMI 52.0; EUR/USD 1.15493, +0.05% today and the second-best G10, -0.72% on the week.",
      forward: "⚖️ Balanced, with both sides getting stronger rather than either resolving. The hawkish side is documented and recent: a unanimous hike, Lagarde calling it a no-brainer, the 2027 inflation projection lifted to 2.5%, 2026 growth upgraded to 0.9%, and no further move expected until October 29, which gives the euro a policy floor nothing on the calendar can test for six weeks. The dovish side is the terms of trade, and it is compounding faster than the policy is helping - EU gas 82.69 is up 3.29% today, 4.35% on the week, 33.89% on the month and 155% on the year, which taxes the same manufacturing economy the ECB just upgraded, and it is why headline HICP is at 3.3% while core falls to 2.4%. A central bank tightening into energy-driven headline inflation while core decelerates is running the same risk the Bank of England is, six weeks behind. The final August HICP tomorrow at 09:00Z should confirm 3.3% and is not an event. What would invalidate: gas sustaining above 90 EUR/MWh, or a composite PMI dropping under 50, would make the October 29 hold look like the start of a pause and take EUR to 0; core re-accelerating above 2.5% with gas stable would take it to +2.",
    },
    {
      ccy: "AUD",
      score: 1,
      verdict: "MIXED",
      tag: "Top carry, copper cause identified",
      drivers: "RBA cash rate 4.35%, the highest on this board, with CPI falling to 3.5% from 3.8% but trimmed-mean core sticky at 3.6% above the 2-3% band, unemployment 4.5% from 4.4%, employment -15,827 after +80,249, wage growth 3.2%, composite PMI 52.7; AUD/USD 0.71322, +0.01% today, -1.18% on the week, +0.38% on the month.",
      forward: "⚖️ Balanced and nudged up within its tier, ahead of Canada, on the commodity mix rather than on anything domestic. Sticky 3.6% core keeps easing off the table and the RBA parked at 4.35% until September 29, so the carry is safe for two weeks; a labour market that shed 15,827 jobs and a consumer confidence reading down to 84.4 from 88.9 keep the hiking case dead. That leaves China and copper, and both read better today than they did on Monday. Copper rose 0.68%, and the week's 5.76% fall now has an identified cause - reports that Washington is reconsidering refined-metal import tariffs, which unwound the arbitrage that had been draining LME stocks - rather than a collapse in Chinese demand. That is a materially better backdrop for the Australian dollar, because a positioning unwind ends while a demand collapse does not. The offset is that China's August mix was supply-side: production beat at 5.2%, retail sales missed at 0.4%, fixed asset investment deepened to -7.2%. What would invalidate: a sustained copper break under 6.20 with Chinese retail sales missing again would take AUD to 0; a Q3 trimmed-mean print holding 3.6% with copper reclaiming 6.80 would put a +2 in play.",
    },
    {
      ccy: "CAD",
      score: 1,
      verdict: "MIXED",
      tag: "Paid by the shock, but the shock paused",
      drivers: "BoC overnight rate 2.25% and frozen until October 28, CPI 3.0% y/y with core rising to 2.4% from 2.3%, unemployment 6.4%, employment -41.7k after +75.1k, services PMI 46.8 and composite 47.8 both in contraction, retail sales -0.8% m/m; USD/CAD 1.39223, CAD -0.03% today as WTI fell 0.99% to 104.779, still +24.00% on the month.",
      forward: "⚖️ Balanced, and moved to the back of the +1 tier today for a precise reason: the Canadian dollar is a derivative of crude, and crude fell. That is not a downgrade, because nothing in the supply picture changed - the Saudi East-West pipeline that bypasses Hormuz is still shut with no Aramco restart timeline, Houthi attacks resumed this week, Libya suspended two oilfields and a pumping station, and US-Iran tanker strikes continue around the strait - and a 0.99% pullback inside a 24.00% month is profit-taking. But it does clarify what the CAD case is and is not. It is energy terms of trade, full stop. It is not domestic strength: services and composite PMIs are both under 50, employment fell 41.7k, retail sales fell 0.8%, and the Bank of Canada is frozen between a 3.0% headline and a contracting economy until October 28. That is why Canada beats the commodity bloc and loses to the dollar, and why the cleanest Canadian expression is CAD/CHF, which has no meeting on either leg this week. What would invalidate: a genuine Hormuz de-escalation or a pipeline restart taking WTI back under 95 would take CAD to 0 quickly; a hot September CPI with crude holding above 105 would put +2 in play.",
    },
    {
      ccy: "JPY",
      score: 1,
      verdict: "MIXED",
      tag: "97% priced, and now crowded long",
      drivers: "BoJ policy rate 1.00% with a move to 1.25% on Friday at 97% in both the economist survey and OIS, CPI 1.9% y/y from 1.6% with core 1.8%, wage growth 4.7% from 4.0%, unemployment 2.4%, GDP 0.4% q/q revised to 1.4% annualised, composite PMI 53.5; USD/JPY 155.157, JPY -0.04% today, -1.05% on the week but still +2.69% on the month.",
      forward: "⚖️ Balanced, and held at +1 after two cuts rather than cut a third time, because the price damage has stopped even though the crowding has not. The direction of the fundamentals is the best on this board - wages accelerating to 4.7%, CPI up to 1.9%, core 1.8%, wholesale prices +7.6%, unemployment 2.4% - and a hike to 1.25% on Friday would be the highest Japanese policy rate since April 1995. None of that is tradeable, which is the whole point. At roughly 97% priced there is nothing left to buy, and speculators have now flipped net long yen for the first time since February 2026, so the trade is both fully priced and crowded. That combination is why the yen sits level with the euro, the Aussie and the Canadian dollar rather than above them, and why the cross book is RANGE nearly throughout - only NZD/JPY survives as a directional short, on a two-point gap. The tradeable content on Friday is the statement language: 89% of analysts see 1.50% by end-March and 62% see 1.75% by mid-2027, so guidance that validates that path is the upside. What would invalidate: a pause attached to Friday's hike sells the yen and takes JPY to 0; an explicit signal toward December takes it to +2 and re-shorts the cross book.",
    },
    {
      ccy: "GBP",
      score: 0,
      verdict: "MIXED",
      tag: "Headline for the hawks, core for the holders",
      drivers: "Bank Rate 3.75% with tomorrow's vote consensus at 3-0-6, August CPI released this morning at 3.1% y/y in line with forecast from 2.9% and monthly 0.5% from 0.3%, but core holding 2.6% against a 2.7% forecast; unemployment 4.9%, employment +67k, average earnings 3.9% from 4.2%, yesterday's claimant count +27.8k against +8.3k; GBP/USD 1.34899, +0.09% and best G10 today, -0.42% and best on the week.",
      forward: "⚖️ Range, and held at 0 because the day's data armed both sides of the committee at once. The hawks - Pill, Greene and Mann, who moved the July vote from 7-2 to 6-3 - get a headline at a fifteen-month high and a monthly rate that nearly doubled to 0.5%. The holders get a core that did not accelerate at all, missing at 2.6%, stacked on top of a claimant count that came in more than three times consensus yesterday with wages decelerating to 3.9%. That is why the 3-0-6 consensus for tomorrow at 11:00Z did not move, and why the Bank's own projection of a peak near 3.2% in Q4 still reads as the central case rather than a warning. The genuinely new information is not in the data, it is in the tape: sterling absorbed a broken labour print on Tuesday and a soft core on Wednesday and finished best on the board on both the day and the week. A currency that will not go down on bad news is being accumulated, which is why GBP/USD SHORT and EUR/GBP LONG are both cut to LOW-MED rather than held. What would invalidate: a fourth hawkish defector tomorrow, or any hint the peak forecast is being revised up, takes GBP to +1; an unchanged 3-0-6 with dovish minutes and a downgraded inflation path is the first real sell signal sterling has carried and takes it to -1.",
    },
    {
      ccy: "CHF",
      score: 0,
      verdict: "WEAKENING",
      tag: "Best data, no yield, capped by its own bank",
      drivers: "SNB policy rate 0.00% with all but one of 41 economists expecting no change on September 24, CPI 0.8% y/y with core 0.4%, unemployment 3.0%, GDP 1.5% q/q and 2.3% annual - the strongest growth mix on this board - manufacturing PMI 57.1 from 53.2 and services 58.3; USD/CHF 0.81831, CHF +0.05% today on a mild gold-led haven bid, still -1.01% on the week.",
      forward: "🔻 Easing in effect if not in name, and the most counter-intuitive entry on this board for a second day. Switzerland has the best fundamentals in this file by a distance and the franc is still unownable, because the policy rate is 0.00% against a Fed going to 4.00% tonight and an ECB that has already gone to 2.50%, and because the SNB has been explicit about its readiness to intervene against appreciation, with sight deposits rising. The bar for going negative again is high now that inflation is picking up off the floor, so September 24 is not about the rate at all - it is about how firmly the intervention language is set. Today's small haven bid, arriving with gold up 0.87% while crude fell, is exactly the appreciation the SNB has said it will lean against, which caps it. The practical consequence is what makes CHF the most useful currency here: it is the only one on the board with no binary event before September 24, which turns it into the clean funding leg while four other central banks report inside 65 hours. What would invalidate: intervention language that disappoints on September 24, or a genuine haven panic that overwhelms the SNB, takes CHF to +1; confirmation of active intervention takes it to -1.",
    },
    {
      ccy: "NZD",
      score: -1,
      verdict: "WEAKENING",
      tag: "Worst again, with GDP tonight",
      drivers: "RBNZ OCR 2.75% after the September 2 hike but expected to hold on October 28 with the next move not priced until December 9, CPI 4.1% y/y driven by imported fuel with core 3.2%, unemployment rising to 5.6% from 5.4%, wage growth only 2.1%, services PMI 51.2; NZD/USD 0.57531, -0.07% and worst G10 today, -1.49% on the week, -2.52% on the month.",
      forward: "🔻 Easing relative to everything around it, and the widest gap on this board at three points from the dollar. The structural case has not changed and does not need to: a central bank that hiked on September 2 purely because Middle East fuel costs were passing into headline inflation, then signalled a pause into October with its own Q4 average OCR projection of 2.81% implying December rather than October for the next move, sitting on 4.1% inflation, 3.2% core, unemployment climbing to 5.6% and wage growth of just 2.1%. Tightening into an imported price shock and then stopping because the domestic economy cannot absorb more is the textbook definition of stagflationary weakness, and the market has been voting on it for a month. The near-term risk is specific and it is an upside one: Q2 GDP tonight at 22:45Z carries a +0.1% consensus against +0.8% previously, but ASB expects 0.3% - above both consensus and the RBNZ's own flat estimate - and leading indicators are said to point to a Q3 recovery. What would invalidate: a GDP print at or above 0.3% would pull December pricing forward and take NZD to 0, especially if it lands after a dovish Fed; a print at or below 0.0% confirms -1 and puts -2 in play.",
    },
  ],

  symbols: [
    {
      sym: "USOIL",
      bias: "LONG",
      conv: "HIGH",
      why: "The only high-conviction position left in this file, and the only one whose thesis does not depend on a central bank speaking in the next three days - WTI 104.779 fell 0.99% today but is +9.09% on the week and +24.00% on the month, with the Saudi East-West pipeline that bypasses Hormuz still shut and no Aramco restart timeline, renewed Houthi strikes on Saudi Arabia, Libya suspending two oilfields and a pumping station, and US-Iran tanker-for-tanker strikes continuing around the strait.",
      risk: "A credible Hormuz de-escalation or an Aramco restart announcement removes the premium faster than it was added; a hawkish dot plot that lifts the dollar hard is a second-order drag, and after a 24% month the position is long enough that any headline gets an outsized reaction.",
    },
    {
      sym: "NZD/USD",
      bias: "SHORT",
      conv: "MEDIUM",
      why: "The widest gap on the board at three points - the dollar at +2 against the currency that has been worst in four of the last five sessions; 0.57531, -0.07% today, -1.49% on the week and -2.52% on the month, with the RBNZ pausing into 4.1% inflation and 5.6% unemployment while the Fed goes to 4.00% tonight.",
      risk: "Cut from HIGH purely on event stacking, not on any change of view: the dot plot at 18:00Z and NZ Q2 GDP at 22:45Z resolve both legs inside five hours, and ASB expects 0.3% against a 0.1% consensus. An intact Fed easing path plus a GDP beat unwinds this from both ends at once and cannot be managed through.",
    },
    {
      sym: "EUR/CHF",
      bias: "LONG",
      conv: "MEDIUM",
      why: "One of three event-free tickets on the board tonight - a hawkish ECB at a 2.50% deposit rate with nothing scheduled until October 29, against a 0.00% SNB that does not meet until September 24 and has signalled it will lean against franc appreciation. Neither leg carries a binary event this week.",
      risk: "A genuine haven panic - a Hormuz escalation that overwhelms the SNB's intervention appetite - bids the franc through the cap; on the other side, EU gas at 82.69 and up 33.89% on the month is a live terms-of-trade tax on the euro leg if it keeps compounding.",
    },
    {
      sym: "AUD/CHF",
      bias: "LONG",
      conv: "MEDIUM",
      why: "The top carry on the board at 4.35% funded at 0.00%, with both central banks parked - the RBA until September 29 and the SNB until September 24 - so the trade is a clean carry expression with no event leg. Copper bouncing 0.68% and the week's fall now attributable to a tariff-review unwind rather than Chinese demand improves the Australian side.",
      risk: "A copper break under 6.20 on renewed Chinese demand weakness, or a haven bid strong enough to overpower the SNB, are the two ways this loses; a sharp risk-off reaction to a hawkish dot plot would hit the Aussie leg indirectly even though neither currency is the dollar.",
    },
    {
      sym: "CAD/CHF",
      bias: "LONG",
      conv: "MEDIUM",
      why: "Upgraded from LOW-MED on the event calendar rather than on new data: with the Bank of Canada frozen until October 28 and the SNB not meeting until September 24, this expresses the energy-exporter-over-funding-currency axis with no binary event on either leg, at a time when almost every other trade here has one.",
      risk: "The Canadian leg is a pure derivative of crude, and crude fell 0.99% today - a real de-escalation or pipeline restart takes WTI under 95 and the trade with it. Canada's domestic data is contracting outright (services PMI 46.8, composite 47.8, employment -41.7k), so there is no second engine if oil stalls.",
    },
    {
      sym: "EUR/NZD",
      bias: "LONG",
      conv: "MEDIUM",
      why: "A two-point gap expressing the top-versus-bottom view without dollar risk - a unanimously hawkish ECB at 2.50% with no meeting until October 29, against an RBNZ that hiked on September 2 and immediately signalled a pause into December while inflation runs at 4.1% and unemployment climbs to 5.6%.",
      risk: "NZ Q2 GDP at 22:45Z is the single event, and the risk is a beat: ASB looks for 0.3% against a 0.1% consensus and the RBNZ's flat estimate. A print at or above 0.3% pulls December pricing forward and squeezes this. Rising EU gas is a slow drag on the euro leg.",
    },
    {
      sym: "AUD/NZD",
      bias: "LONG",
      conv: "MEDIUM",
      why: "The cleanest antipodean expression of the two-point gap: 4.35% carry against 2.75%, an RBA on hold with sticky 3.6% core against an RBNZ that has stopped hiking into 4.1% inflation because the economy cannot take more, and no dollar leg to be resolved by tonight's dot plot.",
      risk: "Both legs are commodity-sensitive so the pair can compress on a broad risk event; the specific risk is NZ Q2 GDP at 22:45Z beating the 0.1% consensus, with ASB at 0.3%. A weak Chinese demand signal would hit the Australian leg independently.",
    },
    {
      sym: "NZD/CAD",
      bias: "SHORT",
      conv: "MEDIUM",
      why: "Short the currency being squeezed by imported fuel costs against the one being paid for them - New Zealand's 4.1% inflation is explicitly Middle East fuel-driven, which is the same shock that is lifting Canada's terms of trade with WTI up 24.00% on the month. A two-point gap with no dollar leg.",
      risk: "Crude fell 0.99% today and the Canadian leg has no domestic engine behind it, with services and composite PMIs both under 50; a Hormuz de-escalation would hit the CAD side while an NZ GDP beat at 22:45Z hits the other, and the two could arrive within hours of each other.",
    },
    {
      sym: "NZD/JPY",
      bias: "SHORT",
      conv: "MEDIUM",
      why: "The only yen cross still carrying a directional bias, on a two-point gap - a BoJ moving to a 31-year-high policy rate on Friday against an RBNZ that has paused into 4.1% inflation, 3.2% core and 5.6% unemployment with only 2.1% wage growth.",
      risk: "Both legs have an event inside 65 hours and both are priced: NZ GDP at 22:45Z with ASB looking for a beat, and a 97%-priced BoJ hike where speculators are already net long yen for the first time since February. A pause attached to Friday's statement sells the yen leg hard.",
    },
    {
      sym: "NZD/CHF",
      bias: "SHORT",
      conv: "MEDIUM",
      why: "The weakest currency on the board sold against the board's cleanest funding leg, with no dollar exposure - an RBNZ on hold until at least October 28 against an SNB that will not move on September 24 and is actively leaning against its own currency's strength.",
      risk: "NZ Q2 GDP at 22:45Z is the one live event and the risk is an upside surprise, with ASB at 0.3% against a 0.1% consensus. A haven bid strong enough to move the franc through the SNB's cap would compound a GDP beat from the other side.",
    },
    {
      sym: "DXY",
      bias: "LONG",
      conv: "MEDIUM",
      why: "99.569, down 0.07% today after two sessions of beating all seven peers, but still +0.76% on the week and higher against all seven over five sessions; the index is EUR 57.6%, JPY 13.6%, GBP 11.9% and CAD 9.1%, and the Fed is the only central bank of that group hiking tonight.",
      risk: "The single largest correlated risk in this file resolves at 18:00Z. The index is -0.07% on the month with an 86-90% hike already priced, so an intact easing path in the dots sells the fact and takes this down with USD/CHF, EUR/USD, AUD/USD and NZD/USD simultaneously.",
    },
    {
      sym: "USD/CHF",
      bias: "LONG",
      conv: "MEDIUM",
      why: "The widest policy-rate gap available anywhere on this board - 4.00% after tonight against 0.00% - with an SNB that has signalled it will intervene against franc appreciation before it meets on September 24. 0.81831, +1.01% on the week despite the franc firming 0.05% today.",
      risk: "Cut from HIGH because the dollar leg is fully event-dependent tonight and the franc caught a haven bid today as gold rose 0.87%. A dovish dot plot plus a Hormuz escalation would hit both legs at once, and the SNB cannot hold the franc down against a genuine panic.",
    },
    {
      sym: "EUR/USD",
      bias: "SHORT",
      conv: "MEDIUM",
      why: "1.15493, +0.05% today but -0.72% on the week, expressing a one-point gap: the Fed goes to 4.00% tonight while the ECB, having hiked to 2.50% on September 10, has nothing scheduled until October 29 - and the euro's energy bill keeps compounding with EU gas +33.89% on the month.",
      risk: "The dot plot at 18:00Z. An intact easing path makes tonight the last hike and the dollar leg unwinds; the euro has also just been the second-best G10 on the day, and a confirmed 3.3% final HICP tomorrow at 09:00Z would harden the ECB's floor.",
    },
    {
      sym: "AUD/USD",
      bias: "SHORT",
      conv: "MEDIUM",
      why: "0.71322, flat at +0.01% today and -1.18% on the week, on a one-point gap - the Fed hiking to 4.00% tonight against an RBA parked at 4.35% until September 29 with a labour market that shed 15,827 jobs and consumer confidence down to 84.4 from 88.9.",
      risk: "The carry differential still favours the Aussie in absolute terms, so this is a momentum and event trade rather than a yield one. A dovish dot plot plus the copper bounce extending on the tariff-review news would reverse it quickly; AUD/USD is +0.38% on the month, unlike most of this board.",
    },
    {
      sym: "USD/JPY",
      bias: "RANGE",
      conv: "MEDIUM",
      why: "155.157, +0.04% today and +1.05% on the week but still -2.69% on the month - two fully-priced central banks facing each other inside 65 hours, with the Fed 86-90% priced for tonight and the BoJ 97% priced for Friday. When both levels are bought, the pair trades levels rather than direction.",
      risk: "Both events are guidance trades, and they point opposite ways: hawkish dots plus a BoJ pause breaks this higher through 156, while an intact Fed easing path plus explicit BoJ guidance toward December breaks it lower. Speculators are net long yen for the first time since February, which skews the squeeze risk upward.",
    },
    {
      sym: "JPYBASKET",
      bias: "RANGE",
      conv: "MEDIUM",
      why: "The opposite ticket to the XXX/JPY pairs, and it rises when the yen strengthens - with JPY scored MIXED at +1 the basket is RANGE by construction. A 97%-priced hike to a 31-year high on Friday has nothing left to buy, and speculators have already flipped net long yen for the first time since February 2026.",
      risk: "Friday's statement language is the whole event: guidance toward 1.50% by end-March, which 89% of analysts already expect, lifts the basket and would justify a directional long; a pause attached to the hike sells the yen across the board and breaks the basket lower.",
    },
    {
      sym: "GBP/NZD",
      bias: "LONG",
      conv: "LOW-MED",
      why: "A one-point gap between a Bank of England whose committee still has three members voting to hike into a 3.1% headline, and an RBNZ that has paused into 4.1% inflation with unemployment rising to 5.6%. Sterling was the best G10 today and the best on the week.",
      risk: "Two events inside 29 hours on opposite legs: NZ Q2 GDP at 22:45Z with ASB looking for a beat against a 0.1% consensus, and the MPC vote at 11:00Z tomorrow where an unchanged 3-0-6 with dovish minutes would undercut the sterling leg.",
    },
    {
      sym: "GBP/USD",
      bias: "SHORT",
      conv: "LOW-MED",
      why: "1.34899, a two-point gap on paper with the Fed at 4.00% tonight against a Bank Rate held at 3.75% - but cut to LOW-MED because the price is not cooperating: sterling was the best G10 today at +0.09% and is still best on the week at -0.42%, absorbing both a broken claimant count and a soft core.",
      risk: "A currency that will not fall on bad news is being accumulated, and this trade is now fighting that. A fourth hawkish MPC defector tomorrow at 11:00Z on top of a 3.1% headline would squeeze it hard; the dot plot at 18:00Z tonight resolves the other leg first.",
    },
    {
      sym: "USD/CAD",
      bias: "LONG",
      conv: "LOW-MED",
      why: "1.39223, +0.85% on the week, a one-point gap with the Fed hiking to 4.00% tonight against a Bank of Canada frozen at 2.25% until October 28 - and Canada's domestic data is contracting outright, with services PMI 46.8, composite 47.8 and employment -41.7k.",
      risk: "The lowest-quality dollar long here because the Canadian leg is a crude derivative, and crude is still +24.00% on the month despite today's 0.99% dip. Any renewed Hormuz escalation bids CAD directly against the trade, and a dovish dot plot hits the other leg simultaneously.",
    },
    {
      sym: "EUR/GBP",
      bias: "LONG",
      conv: "LOW-MED",
      why: "A one-point gap between a unanimously hawkish ECB at a 2.50% deposit rate and a Bank of England expected to hold 3-0-6 tomorrow - but cut from MEDIUM because sterling has now outperformed for two consecutive sessions through genuinely poor data, which is accumulation rather than noise.",
      risk: "The MPC vote at 11:00Z tomorrow is the event, and it is asymmetric against this trade: a fourth hawkish defector on a 3.1% headline would move sterling sharply, while an unchanged 3-0-6 is already fully priced. Rising EU gas is a compounding drag on the euro leg.",
    },
    {
      sym: "GBP/AUD",
      bias: "SHORT",
      conv: "LOW-MED",
      why: "A one-point gap selling a Bank Rate of 3.75% against the highest carry on the board at 4.35%, with the RBA parked until September 29 on sticky 3.6% trimmed-mean core and copper bouncing 0.68% after its tariff-driven weekly fall.",
      risk: "Sterling was the best G10 on the day and the week and is refusing to sell off, which is the immediate problem for this trade; the MPC vote at 11:00Z tomorrow could add a fourth hawk. On the other side, Australian employment fell 15,827 and confidence dropped to 84.4.",
    },
    {
      sym: "GBP/CAD",
      bias: "SHORT",
      conv: "LOW-MED",
      why: "A one-point gap selling sterling against the one G10 economy being paid by the energy shock, with WTI +24.00% on the month and the Saudi East-West pipeline still shut - while the Bank of England is expected to hold at 3-0-6 tomorrow.",
      risk: "Both legs are weak: sterling is outperforming despite poor data, and Canada's domestic economy is contracting with two PMIs under 50 and employment -41.7k. Crude fell 0.99% today, so the CAD engine paused at the same time the GBP leg firmed.",
    },
    {
      sym: "GBP/JPY",
      bias: "SHORT",
      conv: "LOW-MED",
      why: "A one-point gap selling a Bank of England on hold against a Bank of Japan hiking to a 31-year high on Friday, with Japanese wage growth at 4.7% and CPI at 1.9% both accelerating while UK core inflation held flat at 2.6%.",
      risk: "Two central banks in 44 hours on opposite legs, both priced - the MPC at 3-0-6 and the BoJ at 97%. A fourth UK hawk tomorrow or a pause attached to Friday's BoJ statement would each undo this independently, and speculators are already net long yen.",
    },
    {
      sym: "CHF/JPY",
      bias: "SHORT",
      conv: "LOW-MED",
      why: "A one-point gap selling a 0.00% policy rate against a central bank moving to 1.25% on Friday - the franc is capped by an SNB that has signalled intervention against appreciation, while Japanese wages at 4.7% and core CPI at 1.8% are the strongest direction on this board.",
      risk: "Both are haven currencies, so a Hormuz escalation bids both legs and the pair goes nowhere; the franc caught a bid today as gold rose 0.87%. A BoJ pause on Friday against a crowded net-long yen position is the sharper risk.",
    },
    {
      sym: "XAU/USD",
      bias: "RANGE",
      conv: "LOW-MED",
      why: "STOOD DOWN from SHORT into the dot plot, not reversed. Gold 4329.73 rose 0.87% today while WTI fell 0.99% - the first session of this run where bullion rose and crude fell together, inverting the sign that defined the regime. The real-rates thesis is intact and the weekly board still favours the short at -1.56%, but holding a directional metals position through a binary event is a poor 4H risk.",
      risk: "The short comes back immediately if the out-year dots are lifted, which would push real rates higher into a market that has just started buying gold again. The opposite case is worse: an intact easing path plus a Hormuz escalation would run the metal hard, and positioning is crowded long near 228k net contracts.",
    },
    {
      sym: "XCU/USD",
      bias: "RANGE",
      conv: "LOW-MED",
      why: "STOOD DOWN from SHORT on a structural reassessment rather than the 0.68% bounce. Copper 6.4118 fell 5.76% on the week, and the cause is now identified: reports that Washington is reconsidering refined-metal import tariffs knocked futures almost 5% and unwound the arbitrage that was the short's entire engine. Once the catalyst is paid, what remains is a tight physical market.",
      risk: "The physical backdrop argues for upside, not downside: LME live stocks drained near 90,000 tonnes, H1 mine output -1.1% with Chile -6.6%, Indonesian concentrate -32% and DRC -34%, against accelerating data-centre demand. The bear case needs Chinese consumption to keep missing, as August retail sales did at 0.4%.",
    },
    {
      sym: "EUR/JPY",
      bias: "RANGE",
      conv: "LOW-MED",
      why: "Two currencies scored at +1 with hawkish central banks facing each other - an ECB that hiked unanimously to 2.50% on September 10 with nothing until October 29, against a BoJ moving to 1.25% on Friday at 97% priced. No gap means levels, not direction.",
      risk: "Friday's BoJ statement is the only thing that can open a gap here: explicit guidance toward 1.50% by end-March breaks it lower, a pause attached to the hike breaks it higher. EU gas at +33.89% on the month is a slow structural drag on the euro leg.",
    },
    {
      sym: "XAG/USD",
      bias: "RANGE",
      conv: "LOW",
      why: "STOOD DOWN from SHORT and lower conviction than gold, because silver rose more - up 1.48% to 64.584 today - and carries an industrial-demand leg that can decouple it from bullion, which the tight copper market is now supporting. Still -3.99% on the week, so the real-rates case has not been disproven, merely interrupted ahead of a binary event.",
      risk: "Managed-money positioning is crowded long at roughly 228,000 net contracts into the dot plot, which cuts both ways violently: a hawkish surprise triggers a liquidation far larger than the fundamentals warrant, while a dovish one runs it. That two-sided tail is precisely why this is RANGE rather than a directional bet.",
    },
    {
      sym: "GER40",
      bias: "RANGE",
      conv: "LOW",
      why: "Moved up from SHORT: the DAX is 25489, +0.34% today, and the crude pullback that pressured it on Monday has reversed with Brent down 0.57% - a genuine tailwind for an energy-importing index. The offsetting headwinds are unchanged, with a hawkish ECB at 2.50% and German gas up 29.87% on the month.",
      risk: "The index is caught between two energy prices moving in opposite directions - falling crude helps while gas at 80.96 keeps climbing on the month - and a Hormuz escalation would reverse the crude leg immediately. AI-related concerns hit Infineon and Siemens Energy hard this week.",
    },
    {
      sym: "GBP/CHF",
      bias: "RANGE",
      conv: "LOW",
      why: "Both currencies scored at 0 for opposite reasons - sterling because its data armed both sides of a split MPC, the franc because excellent data is attached to a 0.00% rate and a central bank capping it. No gap, so this trades levels.",
      risk: "The MPC vote at 11:00Z tomorrow is the only scheduled catalyst on either leg before September 24, and a fourth hawkish defector would open a gap higher; a haven bid that overwhelms the SNB opens one lower.",
    },
    {
      sym: "EUR/AUD",
      bias: "RANGE",
      conv: "LOW",
      why: "Two currencies at +1 with genuinely offsetting cases - a hawkish ECB at 2.50% whose economy is being taxed by gas up 33.89% on the month, against the board's top carry at 4.35% whose economy depends on a Chinese demand picture that keeps missing on consumption.",
      risk: "Neither central bank meets before September 29, so this needs a commodity move to break: sustained copper strength on the tight physical market would favour the Aussie leg, while EU gas sustaining above 90 EUR/MWh would break it the other way.",
    },
    {
      sym: "EUR/CAD",
      bias: "RANGE",
      conv: "LOW",
      why: "Both at +1, and the two legs are now moving against each other in an unusually clean way - the euro is taxed by rising energy with gas up 33.89% on the month, while Canada is paid by it with WTI up 24.00%. Those cancel, which is what a zero gap means.",
      risk: "This is effectively a spread on the direction of the energy shock: escalation favours the Canadian leg, de-escalation the European one. Crude fell 0.99% today while EU gas rose 3.29%, which is the one configuration that moves both legs the same way.",
    },
    {
      sym: "AUD/CAD",
      bias: "RANGE",
      conv: "LOW",
      why: "Both at +1 and both commodity currencies, but on opposite sides of the split inside the complex - Australia on industrial metals, where copper bounced 0.68% today after a tariff-driven 5.76% weekly fall, and Canada on energy, where WTI slipped 0.99% after a 24.00% month.",
      risk: "The pair is a direct expression of the metals-versus-energy split that has defined this regime, so it breaks when that split narrows. A Hormuz de-escalation favours the Aussie leg; renewed Chinese consumption weakness favours the Canadian one.",
    },
    {
      sym: "AUD/JPY",
      bias: "RANGE",
      conv: "LOW",
      why: "Both at +1, and the classic carry expression is neutralised by the event calendar - the RBA holds 4.35% until September 29 while the BoJ hikes to 1.25% on Friday at 97% priced, so the carry narrows on a move everyone already owns.",
      risk: "Friday's BoJ guidance is the only scheduled catalyst: a pause attached to the hike sells the yen and breaks this higher, explicit guidance toward 1.50% breaks it lower. Speculators are net long yen for the first time since February, which skews toward a squeeze higher.",
    },
    {
      sym: "CAD/JPY",
      bias: "RANGE",
      conv: "LOW",
      why: "Both at +1 with offsetting stories - Canada gains from crude that is up 24.00% on the month but has a domestic economy in contraction with two PMIs under 50, while Japan has the best fundamental direction on the board attached to a fully-priced hike.",
      risk: "Two different shocks can open a gap here in opposite directions: a Hormuz escalation lifts the Canadian leg through crude, while Friday's BoJ statement moves the yen leg. Both could land inside 65 hours, which is the argument for levels over direction.",
    },
  ],

  catalysts: [
    {
      date: "Sep 16",
      event: "UK CPI y/y, core CPI and monthly CPI (ONS, ahead of the MPC)",
      impact: "high",
      note: "RELEASED this morning at 06:00Z and TE-verified: headline 3.1% y/y against a 3.1% forecast and 2.9% previously, the monthly rate 0.5% from 0.3%, and core holding 2.6% against a 2.7% forecast. Exactly in line on the headline is what yesterday's file said would preserve both the 3-0-6 vote consensus and the score, and it did. The core undershoot is the detail that matters: a fifteen-month-high headline arms the three MPC hawks while an unaccelerating core arms the six holders, so nothing moved a vote 29 hours before the decision. GBP holds 0.",
      when: "2026-09-16T06:00:00Z",
    },
    {
      date: "Sep 16",
      event: "US Federal Funds Rate, FOMC Statement and Summary of Economic Projections (Federal Reserve)",
      impact: "high",
      note: "TODAY at 18:00Z and the single biggest event on this board. ForexFactory and TE both carry a 4.00% forecast against 3.75% previously, and CME FedWatch has held 86-90% since September 11, so the hike is bought and the dot plot is the entire trade. The unresolved tension: the Fed's published rows - 3.8% current year, 3.6% first, 3.4% second, 3.1% third, 3.1% longer-run - describe a path that cuts after today, against a futures strip pricing two more increases by year end. Out-year dots lifted takes USD to +3; an intact easing path is the sell-the-fact scenario that hits nine positions here at once.",
      when: "2026-09-16T18:00:00Z",
    },
    {
      date: "Sep 16",
      event: "FOMC Press Conference with Chair Warsh (Federal Reserve)",
      impact: "high",
      note: "TODAY at 18:30Z, 30 minutes after the projections. Warsh has abandoned his predecessor's forward-guidance approach entirely and has not given guidance since Jackson Hole on August 28, so the base case is that he declines to characterise the path and refers back to the dots. That makes the press conference a volatility event rather than an information one - the risk is an unscripted characterisation of whether an oil-driven inflation impulse should be looked through, given core CPI at 2.4% is the lowest since March 2021.",
      when: "2026-09-16T18:30:00Z",
    },
    {
      date: "Sep 16",
      event: "New Zealand Q2 GDP q/q (Stats NZ)",
      impact: "high",
      note: "TONIGHT at 22:45Z, five hours after the Fed, and the second leg of the file's largest event stack. ForexFactory carries +0.1% against +0.8% previously. The specific risk is an upside surprise: ASB expects 0.3%, above both the consensus and the RBNZ's own flat estimate, and leading indicators are reported to point to a Q3 recovery. A print at or above 0.3% would pull December OCR pricing forward and take NZD to 0, which is why NZD/USD was cut from HIGH to MEDIUM; at or below 0.0% confirms -1 and puts -2 in play.",
      when: "2026-09-16T22:45:00Z",
    },
    {
      date: "Sep 17",
      event: "UK Official Bank Rate, Monetary Policy Summary and MPC vote split (Bank of England)",
      impact: "high",
      note: "Tomorrow at 11:00Z. ForexFactory carries a 3.75% hold with the vote consensus unchanged at 3-0-6, three for a hike to 4.00% and six to hold - the same split as July, when Mann joined Greene and Pill. This morning's CPI did not move it: the 3.1% headline supports the hawks, the flat 2.6% core supports the holders. The tradeable content is the vote and the minutes, not the level. A fourth defector takes GBP to +1 and squeezes a sterling that is already the best G10 of the week; an unchanged split with dovish minutes is the first real sell signal sterling has carried.",
      when: "2026-09-17T11:00:00Z",
    },
    {
      date: "Sep 18",
      event: "BoJ Policy Rate and Monetary Policy Statement (Bank of Japan)",
      impact: "high",
      note: "Friday at 02:30Z. ForexFactory carries 1.25% against 1.00% previously, 97% of surveyed economists agree, and OIS pricing is at roughly 97% - a move to the highest Japanese policy rate since April 1995. Supporting it: Q2 GDP revised to 1.4% annualised, July real wages +2.4% (strongest since 2021), August wholesale prices +7.6%. The problem is that none of this is tradeable at 97% priced with speculators net long yen for the first time since February 2026. The content is the guidance: 89% of analysts see 1.50% by end-March. A pause attached to the hike sells the yen and takes JPY to 0.",
      when: "2026-09-18T02:30:00Z",
    },
    {
      date: "Sep 18",
      event: "BoJ Press Conference with Governor Ueda (Bank of Japan)",
      impact: "high",
      note: "Friday at 05:30Z, three hours after the decision, and the more important of the two for the yen given the level is fully priced. The question is whether the Bank frames 1.25% as a waypoint toward 1.50% by end-March - which 89% of analysts expect and which would validate the crowded long - or as a destination requiring a pause to assess. With the yen already carrying speculative net longs for the first time since February, dovish framing produces a sharper move than hawkish framing does.",
      when: "2026-09-18T05:30:00Z",
    },
    {
      date: "Sep 15",
      event: "UK Claimant Count Change (ONS labour market overview)",
      impact: "high",
      note: "RELEASED yesterday at 06:00Z. TE-verified: +27.8k against an +8.3k forecast and -11.8k previously, a 39.6k swing in one month, alongside average earnings decelerating to 3.9% from 4.2%, unemployment holding 4.9% and employment change +67k from +83k. This broke the labour leg of the BoE hawkish case, but sterling fell only 0.17% and has since gone on to lead the board. Read together with today's flat core, the two prints give the six MPC holders their argument while the 3.1% headline gives the three hawks theirs.",
      when: "2026-09-15T06:00:00Z",
    },
    {
      date: "Sep 14",
      event: "Canada CPI m/m, Median CPI y/y and Trimmed CPI y/y (Statistics Canada)",
      impact: "high",
      note: "RELEASED Monday at 12:30Z. TE-verified: headline 3.0% y/y in line, the monthly rate -0.1% against a 0.0% forecast and +0.5% previously, core rising to 2.4% y/y from 2.3%, trimmed-mean holding 1.9% and median 2.0%. The stated invalidation required a monthly print below 0.0% AND trimmed-mean under 1.9% - half met, so CAD held +1. The Bank of Canada stays frozen at 2.25% until October 28, which is why the Canadian dollar trades as a crude derivative rather than on its own data.",
      when: "2026-09-14T12:30:00Z",
    },
    {
      date: "Sep 17",
      event: "Euro area final August HICP and core (Eurostat)",
      impact: "med",
      note: "Tomorrow at 09:00Z. TE carries a 3.3% forecast, confirming the September 1 flash which came in at 3.3% against a 2.9% consensus, with core easing to 2.4% from 2.5% and energy inflation at 14.3%. A confirmation rather than an event - the flash already did the work. What matters for the euro is the split it documents: headline driven by energy while core decelerates, which is the same configuration the Bank of England is dealing with, and which will shape the October 29 debate far more than the level does.",
    },
    {
      date: "Sep 24",
      event: "SNB policy rate decision and monetary policy assessment (Swiss National Bank)",
      impact: "med",
      note: "07:30Z. TE carries both a 0% consensus and a 0% forecast, and all but one of 41 economists in the Reuters poll expect no change through 2026. With CPI at 0.8% and picking up off the floor, the bar for returning to negative rates is high, so the decision is about the other lever: how firmly the SNB sets its intervention language against franc appreciation, with sight deposits rising. This is the only scheduled event on the CHF leg of EUR/CHF, AUD/CHF and CAD/CHF, which is precisely what makes those three the cleanest trades this week.",
      when: "2026-09-24T07:30:00Z",
    },
    {
      date: "Sep 29",
      event: "RBA cash rate decision and statement (Reserve Bank of Australia)",
      impact: "med",
      note: "04:30Z, after the September 28-29 board meeting. TE carries no change from 4.35%, which is the highest policy rate on this board and the entire carry case for the Australian dollar. Trimmed-mean core at 3.6% is still above the 2-3% target band, which rules out easing, while employment at -15,827 and consumer confidence down to 84.4 from 88.9 rule out hiking. The statement's read on Chinese demand matters more than the rate.",
      when: "2026-09-29T04:30:00Z",
    },
    {
      date: "Oct 28",
      event: "Bank of Canada overnight rate decision with Monetary Policy Report",
      impact: "med",
      note: "TE carries no change from 2.25%. The Bank is frozen between a 3.0% headline with core rising to 2.4%, and a domestic economy that is contracting outright - services PMI 46.8, composite 47.8, employment -41.7k, retail sales -0.8% m/m. The Monetary Policy Report is where the energy windfall gets quantified against that weakness, and it is the first scheduled opportunity for CAD to trade on something other than the price of WTI.",
    },
    {
      date: "Oct 28",
      event: "RBNZ Official Cash Rate review (Reserve Bank of New Zealand)",
      impact: "med",
      note: "01:00Z. TE carries a 2.75% forecast, and the RBNZ's own Q4 average OCR projection of 2.81% is consistent with a hold here followed by a 25bp hike on December 9. That sequencing is the core of the short case: a central bank that raised rates on September 2 because of imported fuel costs and then immediately stopped, with inflation at 4.1%, unemployment at 5.6% and wage growth at only 2.1%. Tonight's Q2 GDP is the first input that can change it.",
      when: "2026-10-28T01:00:00Z",
    },
    {
      date: "Oct 29",
      event: "ECB Governing Council monetary policy meeting",
      impact: "med",
      note: "The next scheduled ECB decision after the unanimous September 10 hike to a 2.50% deposit facility rate, and TE carries no move before it. The debate will be whether an energy-driven headline at 3.3% justifies further tightening while core decelerates to 2.4% and EU gas - up 33.89% on the month and 155% on the year - taxes the manufacturing base the Bank just upgraded to 0.9% growth for 2026. Six weeks with no meeting is what gives the euro its policy floor.",
    },
    {
      date: "Rolling",
      event: "Saudi East-West pipeline outage and Strait of Hormuz tanker conflict",
      impact: "med",
      note: "The supply engine behind WTI at 104.779 and Brent at 108.126. The East-West pipeline - the route that bypasses Hormuz - remains shut after a drone attack with no Aramco restart timeline; Houthi strikes on Saudi Arabia resumed this week; Libya's national oil company has suspended two oilfields and a pumping station amid protests; and the US and Iran are exchanging tanker-for-tanker strikes around the strait under a policy approved this month. Today's 0.99% pullback is profit-taking inside a 24.00% month, not a resolution. This is the USOIL LONG thesis and the CAD case in one line.",
    },
    {
      date: "Rolling",
      event: "US refined copper tariff review and LME inventory drawdown",
      impact: "med",
      note: "The identified cause of copper's 5.76% weekly fall and the reason XCU is stood down to RANGE. Reports that Washington is reconsidering the planned refined-metal import tariffs knocked futures almost 5% in a session, unwinding the COMEX-LME arbitrage that had pulled hundreds of thousands of tonnes toward the US. What is left underneath is tight: LME live stocks near 90,000 tonnes, H1 mine output -1.1% with Chile -6.6%, Indonesian concentrate -32% and DRC -34%. A short whose catalyst has already been paid, standing in front of that inventory, is not a short to press.",
    },
    {
      date: "Rolling",
      event: "European gas prices and the euro area terms of trade",
      impact: "med",
      note: "EU gas at 82.69 EUR/MWh is up 3.29% today, 4.35% on the week, 33.89% on the month and about 155% on the year, with German gas at 80.96 up 29.87% on the month. This is the direct mechanism converting the Middle East supply shock into a euro area problem - it is why August HICP printed 3.3% with energy inflation at 14.3% while core fell to 2.4%, and it is the single largest structural drag on EUR and on GER40. A sustained break above 90 would make the October 29 hold look like the start of a pause.",
    },
    {
      date: "Rolling",
      event: "Precious metals positioning into the FOMC",
      impact: "med",
      note: "Managed-money positioning is crowded long at roughly 228,000 net contracts going into tonight's dot plot, and both metals turned higher today for the first time in the run - gold 4329.73 up 0.87%, silver 64.584 up 1.48% - while crude fell. That combination of a crowded long and a two-sided binary event is why XAU and XAG are stood down to RANGE rather than held short: a hawkish surprise triggers a liquidation larger than the fundamentals justify, and a dovish one runs the metal into the positioning.",
    },
    {
      date: "Rolling",
      event: "Chinese activity data and the industrial metals complex",
      impact: "low",
      note: "August was a supply-side China and it explains the split inside the commodity complex: industrial production beat at 5.2% against a 4.8% consensus, retail sales missed at 0.4% against 0.8%, fixed asset investment deepened to -7.2% year-to-date and new home prices stayed weak. More output and less domestic consumption is the configuration that keeps energy bid and industrial metals capped, and it is the main external input into the Australian dollar between now and the September 29 RBA meeting.",
    },
    {
      date: "Rolling",
      event: "Japanese speculative positioning ahead of the BoJ",
      impact: "low",
      note: "Speculators have flipped net long yen for the first time since February 2026, which is the positioning fact behind the two downgrades this file made to JPY earlier in the week. It means a 97%-priced hike has no marginal buyer left, and it skews the risk around Friday's statement toward a sharper move on dovish framing than on hawkish. It is also the reason the yen-cross book is RANGE almost throughout rather than short.",
    },
    {
      date: "Oct 28",
      event: "Next FOMC meeting after today (Federal Reserve)",
      impact: "low",
      note: "The futures strip prices two quarter-point increases by year end, which means one more after today at either this meeting or in December. Whether that pricing survives depends entirely on tonight's out-year dots, since the Fed's own published path of 3.6% for the first year and 3.4% for the second implies cuts rather than hikes. This is the meeting where the gap between the committee's projections and the market's gets settled.",
    },
    {
      date: "Dec 9",
      event: "RBNZ December Monetary Policy Statement",
      impact: "low",
      note: "The meeting where the RBNZ's own Q4 average OCR projection of 2.81% implies the next 25bp hike, after an expected hold on October 28. The kiwi short is structurally a bet that this gets pushed back rather than pulled forward, because the domestic economy - 5.6% unemployment, 2.1% wage growth, Q2 GDP forecast at +0.1% - cannot absorb more tightening even with headline inflation at 4.1%. Tonight's GDP print is the first test of that.",
    },
  ],

  geopolitics: "The oil shock is now seven months old and it is still the transmission mechanism through which everything else on this board is priced. Iran effectively closed the Strait of Hormuz - roughly 20% of global seaborne oil - in retaliation for the US-Israeli strikes that began on February 28, and the conflict has since migrated almost entirely to sea. In the last fortnight the United States has adopted an explicit tanker-for-tanker policy, striking three Iranian tankers in a single weekend while the IRGC claims strikes on three tankers and three US-linked vessels and has fired a ballistic missile toward US warships near the strait. Both sides are now contesting control of the waterway directly rather than through proxies, which is a materially harder situation to de-escalate than the proxy phase was. Layered on top of that are three separate supply interruptions that have nothing to do with Iranian action: Saudi Arabia's East-West pipeline - the very route built to bypass Hormuz - has been shut since a drone attack on September 11 with no restart timeline from Aramco, Houthi strikes on Saudi Arabia resumed this week, and Libya's national oil company has suspended two oilfields and a pumping station amid protests. That is why WTI is 104.779 and up 24.00% on the month, and why today's 0.99% pullback should be read as profit-taking rather than as the start of a resolution - nothing in the physical picture changed today. The FX transmission runs four ways and today it produced an unusual configuration. First, it is a terms-of-trade shock, and it sorts the board accordingly: Canada is the only G10 economy paid by it, which is the whole CAD case and the reason Canada beats the commodity bloc despite a domestic economy with two PMIs under 50, while the euro area is the most directly taxed, with EU gas at 82.69 up 33.89% on the month and about 155% on the year, feeding an August HICP of 3.3% with energy inflation at 14.3% while core fell to 2.4%. New Zealand sits at the far end of that same axis: its 4.1% headline inflation is explicitly imported fuel cost, which is why the RBNZ hiked on September 2 and then stopped. Second, it is an inflation shock that central banks are having to decide whether to look through, and they are splitting on it - the Fed hikes into it tonight, the ECB hiked into it on September 10, the BoE has three of nine members wanting to, and the RBNZ hiked once and then paused. Third, the haven channel, which is where today differed. For the entire run to date bullion had failed to respond, because the insurance premium was being paid in crude rather than metal and because real rates were rising underneath it. Today gold rose 0.87% and silver 1.48% while crude fell - the first inversion of that pattern - which reads as pre-event hedging rather than a change in the geopolitical assessment, but it is enough to stand the metal shorts down into the dot plot. Fourth, the franc. Switzerland is the classic recipient of a Middle East haven bid and it has not been allowed to receive one, because the SNB has signalled an explicit willingness to intervene against appreciation, with sight deposits rising ahead of the September 24 meeting. That is what converts the best fundamental data on this board into the cleanest funding currency on it. The tail risk to watch is unchanged in shape and slightly sharper in degree: a genuine closure of Hormuz rather than the current contested passage would take crude sharply higher and force every currency here to be re-sorted by energy balance rather than by policy rate, while a credible ceasefire or an Aramco restart would unwind the USOIL LONG, the CAD case and the NZD short simultaneously.",

  macro: {
    USD: {
      inflation: { value: "3.4%", trend: "stable", note: "Aug CPI, core 2.4%", hist: [3.8, 4.2, 3.5, 3.5, 3.4, 3.4] },
      growth: { value: "2.1%", trend: "falling", note: "Q2 annual", hist: [2.7, 2.1, 2.7, 2.1, 2.7, 2.1] },
      unemployment: { value: "4.1%", trend: "stable", note: "Aug rate", hist: [4.3, 4.3, 4.3, 4.2, 4.1, 4.1] },
      jobs: { value: "+162k", trend: "rising", note: "Aug payrolls", hist: [214, 179, 129, 20, 21, 162] },
      rates: { value: "3.75%", trend: "stable", note: "Fed upper bound", hist: [3.25, 3.5, 3.5, 3.75, 3.75, 3.75] },
    },
    EUR: {
      inflation: { value: "3.3%", trend: "rising", note: "Aug HICP, core 2.4%", hist: [3.2, 3.2, 2.8, 2.9, 2.9, 3.3] },
      growth: { value: "1.2%", trend: "rising", note: "Q2 annual", hist: [1.1, 1, 0.9, 1.2, 0.6, 1.2] },
      unemployment: { value: "6.4%", trend: "stable", note: "Jul rate", hist: [6.4, 6.3, 6.3, 6.3, 6.4, 6.4] },
      jobs: { value: "+0.1%", trend: "stable", note: "Q2 employment", hist: [0.3, 0.2, 0.1, 0.1, 0.1, 0.1] },
      rates: { value: "2.50%", trend: "rising", note: "ECB deposit facility", hist: [2, 2, 2, 2, 2.25, 2.5] },
    },
    GBP: {
      inflation: { value: "3.1%", trend: "rising", note: "Aug CPI, core 2.6%", hist: [3.4, 3.4, 2.8, 2.6, 2.9, 3.1] },
      growth: { value: "1.2%", trend: "rising", note: "Q2 annual", hist: [1.1, 1, 0.8, 1.1, 0.9, 1.2] },
      unemployment: { value: "4.9%", trend: "stable", note: "Jul rate", hist: [5.1, 5.2, 5.2, 4.9, 4.9, 4.9] },
      jobs: { value: "+67k", trend: "falling", note: "Jul employment; Aug claims +27.8k", hist: [30, 84, 99, 147, 83, 67] },
      rates: { value: "3.75%", trend: "stable", note: "BoE Bank Rate", hist: [3.5, 3.75, 3.75, 3.75, 3.75, 3.75] },
    },
    JPY: {
      inflation: { value: "1.9%", trend: "rising", note: "Jul CPI, core 1.8%", hist: [2, 1.8, 1.6, 1.5, 1.6, 1.9] },
      growth: { value: "0.7%", trend: "rising", note: "Q2 annual", hist: [0.9, 1.1, 1.3, 0.6, 0.5, 0.7] },
      unemployment: { value: "2.4%", trend: "falling", note: "Jul rate", hist: [2.6, 2.5, 2.5, 2.5, 2.5, 2.4] },
      jobs: { value: "+4.7%", trend: "rising", note: "Jul wage growth", hist: [3.1, 4.1, 2.9, 3.3, 4, 4.7] },
      rates: { value: "1.00%", trend: "rising", note: "BoJ policy rate", hist: [0.5, 0.5, 0.75, 0.75, 1, 1] },
    },
    AUD: {
      inflation: { value: "3.5%", trend: "falling", note: "Jul CPI, trimmed 3.6%", hist: [3.8, 3.9, 4.2, 4, 3.8, 3.5] },
      growth: { value: "2.1%", trend: "falling", note: "Q2 annual", hist: [2.1, 2.2, 2.4, 2.5, 2.5, 2.1] },
      unemployment: { value: "4.5%", trend: "rising", note: "Jul rate", hist: [4.2, 4.3, 4.4, 4.4, 4.4, 4.5] },
      jobs: { value: "-15.8k", trend: "falling", note: "Jul employment", hist: [30, 20, -41, 44, 80.2, -15.8] },
      rates: { value: "4.35%", trend: "stable", note: "RBA cash rate", hist: [4.1, 4.1, 4.35, 4.35, 4.35, 4.35] },
    },
    NZD: {
      inflation: { value: "4.1%", trend: "rising", note: "Q2 CPI, core 3.2%", hist: [2.3, 2.5, 2.7, 3.1, 3.1, 4.1] },
      growth: { value: "1.5%", trend: "stable", note: "Q1 annual", hist: [-0.5, -0.7, 0.3, 1.3, 1.5, 1.5] },
      unemployment: { value: "5.6%", trend: "rising", note: "Q2 rate", hist: [5.1, 5.3, 5.4, 5.4, 5.4, 5.6] },
      jobs: { value: "+0.5%", trend: "rising", note: "Q2 employment", hist: [-0.1, 0, 0.1, 0.5, 0.2, 0.5] },
      rates: { value: "2.75%", trend: "rising", note: "RBNZ official cash rate", hist: [2.25, 2.25, 2.25, 2.25, 2.5, 2.75] },
    },
    CAD: {
      inflation: { value: "3.0%", trend: "stable", note: "Aug CPI, core 2.4%", hist: [2.8, 3.2, 3.2, 2.8, 3, 3] },
      growth: { value: "1.1%", trend: "rising", note: "Q2 annual", hist: [1.7, 1.4, 0.9, 0.6, 0.1, 1.1] },
      unemployment: { value: "6.4%", trend: "stable", note: "Aug rate", hist: [6.7, 6.9, 6.6, 6.5, 6.4, 6.4] },
      jobs: { value: "-41.7k", trend: "falling", note: "Aug employment", hist: [15, 14.1, -17.7, 18, 75.1, -41.7] },
      rates: { value: "2.25%", trend: "stable", note: "BoC overnight rate", hist: [2.25, 2.25, 2.25, 2.25, 2.25, 2.25] },
    },
    CHF: {
      inflation: { value: "0.8%", trend: "rising", note: "Aug CPI, core 0.4%", hist: [0.4, 0.6, 0.6, 0.5, 0.4, 0.8] },
      growth: { value: "2.3%", trend: "rising", note: "Q2 annual", hist: [1.6, 1.4, 1.2, 0.8, 0.4, 2.3] },
      unemployment: { value: "3.0%", trend: "stable", note: "Aug rate", hist: [2.7, 2.8, 2.8, 3, 2.9, 3] },
      jobs: { value: "+0.5%", trend: "rising", note: "Q2 employment", hist: [0.2, 0.2, 0.3, 0.4, 0.3, 0.5] },
      rates: { value: "0.00%", trend: "stable", note: "SNB policy rate", hist: [0, 0, 0, 0, 0, 0] },
    },
  },
};
